server.port=9003
#eureka.client.service-url.defaultZone=http://host.docker.internal:9000/eureka/
##eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=orders-service